sudo: required
services:
  - docker

before_install:
  - docker build -t react-app -f Dockerfile.dev .

script:
  - docker run react-app npm run test -- --coverage

deploy:
  provider: elasticbeansstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
